name: Docker

on:
  push:
    branches:
      - master
    tags:
      - v*
env:
  IMAGE_NAME: cd-management-bot
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2
      - 
        name: Calculate Publishing Variables
        run: |
          # docker.pkg.github.com/
          IMAGE_ID=${{ github.repository }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          VERSION=0.1.${{github.run_number}}

          echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV

          echo "IMAGE_ID=$IMAGE_ID"
          echo "VERSION=$VERSION"
      - 
        name: Build Bot
        run: docker build -t cdmgmtbot .
      - 
        name: Echoing the publishing Variables
        run: |
          echo IMAGE_ID="${{env.IMAGE_ID}}"
          echo VERSION="${{env.VERSION}}"
      - 
        name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - 
        name: Push cdmgmtbot image
        run: |
          CURRENT_ID=$IMAGE_ID
          # CURRENT_ID=jkamsker/coderdojo-discord-moderator/CDManagementBot
          docker tag cdmgmtbot $CURRENT_ID:$VERSION
          docker tag cdmgmtbot $CURRENT_ID:latest

          docker push $CURRENT_ID:$VERSION
          docker push $CURRENT_ID:latest